In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import zipfile
import io

In [3]:
url = "https://ecobici.cdmx.gob.mx/wp-content/uploads/2026/08/public_data_web_2026-07.csv"
csv_file_name="2026-07.csv"
print("\n Fase 1: Extracción de datos")
try:
    response = requests.get(url)
    response.raise_for_status()  # Check for HTTP errors
    print("Descarga exitosa del archivo CSV.")
except requests.exceptions.Timeout:
    print("Error: La solicitud ha excedido el tiempo de espera.")
except requests.exceptions.RequestException as e:
    print(f"Error al descargar el archivo CSV: {e}")
    df_raw=pd.DataFrame()  # Create an empty DataFrame in case of error

 Fase 1: Extracción de datos
Descarga exitosa del archivo CSV.

In [5]:
with open(csv_file_name, 'wb') as f:
    f.write(response.content)
print(f"Archivo {csv_file_name} descargado y guardado correctamente.")

print(f"Lyendo el archivo CSV {csv_file_name}...")
df_raw = pd.read_csv(csv_file_name)
print("Archivo CSV leído correctamente.")
print(f"Se cargaron{df_raw.shape[0]} filas y {df_raw.shape[1]} columnas.")
display(df_raw.head(80))

Archivo 2026-07.csv descargado y guardado correctamente.
Lyendo el archivo CSV 2026-07.csv...
Archivo CSV leído correctamente.
Se cargaron1493484 filas y 9 columnas.

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,F,26.0,5552989,085,30/06/2026,23:43:41,503,01/07/2026,00:00:00
1,M,33.0,5128335,259,30/06/2026,23:52:28,266-267,01/07/2026,00:00:00
2,M,34.0,8647703,040,30/06/2026,23:41:57,011,01/07/2026,00:00:03
3,M,34.0,5633250,492,30/06/2026,23:56:52,489,01/07/2026,00:00:03
4,O,41.0,8516015,133,30/06/2026,23:31:01,345,01/07/2026,00:00:05
...,...,...,...,...,...,...,...,...,...
75,M,43.0,2409894,130,30/06/2026,23:46:56,109,01/07/2026,00:01:44
76,?,25.0,5717962,134,30/06/2026,23:10:12,614,01/07/2026,00:01:45
77,M,34.0,8316747,476,30/06/2026,23:49:45,250,01/07/2026,00:01:48
78,M,31.0,2020758,135,30/06/2026,23:54:41,565,01/07/2026,00:01:52
79,F,30.0,3907052,581,30/06/2026,23:52:09,581,01/07/2026,00:01:52

# Transofrmacion

In [6]:
df =df_raw.copy()

df['Fecha_Retiro']= pd.to_datetime(df['Fecha_Retiro'], dayfirst=True, errors='coerce')
df["Fecha_Arribo"]= pd.to_datetime(df["Fecha_Arribo"], dayfirst=True, errors='coerce')
display(df.head(80))

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,F,26.0,5552989,085,2026-06-30,23:43:41,503,2026-07-01,00:00:00
1,M,33.0,5128335,259,2026-06-30,23:52:28,266-267,2026-07-01,00:00:00
2,M,34.0,8647703,040,2026-06-30,23:41:57,011,2026-07-01,00:00:03
3,M,34.0,5633250,492,2026-06-30,23:56:52,489,2026-07-01,00:00:03
4,O,41.0,8516015,133,2026-06-30,23:31:01,345,2026-07-01,00:00:05
...,...,...,...,...,...,...,...,...,...
75,M,43.0,2409894,130,2026-06-30,23:46:56,109,2026-07-01,00:01:44
76,?,25.0,5717962,134,2026-06-30,23:10:12,614,2026-07-01,00:01:45
77,M,34.0,8316747,476,2026-06-30,23:49:45,250,2026-07-01,00:01:48
78,M,31.0,2020758,135,2026-06-30,23:54:41,565,2026-07-01,00:01:52
79,F,30.0,3907052,581,2026-06-30,23:52:09,581,2026-07-01,00:01:52